USE OSWORKS;

CREATE TABLE endereco (
	ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BAIRRO VARCHAR(100) NOT NULL,
    CEP CHAR(10) NOT NULL,
    COMPLEMENTO VARCHAR(50),
    LOGRADOURO VARCHAR(20),
    NUMERO INT NOT NULL,
    CIDADE_ID BIGINT NOT NULL,
    CLIENTE_ID BIGINT NOT NULL
);
ALTER TABLE endereco ADD CONSTRAINT FK_ENDERECO_CIDADE
FOREIGN KEY (CIDADE_ID) REFERENCES 	CIDADE(ID);

ALTER TABLE endereco ADD CONSTRAINT FK_ENDERECO_CLIENTE
FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID);